# <span style="color:red"> QTM 151 - Practice Quiz </span>

<font size = 5>

**Submit as an HTML file** (see images below)

<font size = 3>

Step 1: Click the 3 dots in the toolbar for "More Actions"

<img src="practice_quiz_figures/step1.png" alt="drawing" width = "600"/>

***
Step 2: Choose "export"

<img src="practice_quiz_figures/step2.png" alt="drawing" width = "600"/>

***
Step 3: Select "HTML" from the dropdown window

<img src="practice_quiz_figures/step3.png" alt="drawing" width = "600"/>

***
Step 4: Select "Export" in the pop-up window.

<img src="practice_quiz_figures/step4.png" alt="drawing" width = "300"/>

Upload the .html file as your submission

<font size="5"> 

Print your name below

In [1]:
# Write your answer here

print("Gabe Vu")

Gabe Vu

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should work as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [3]:
# Write your answer here:
print('I will abide my Emorys code of conduct')

I will abide my Emorys code of conduct

<font size = "5">

Import pandas

In [4]:
import pandas as pd


<font size = "5">

(1) Replace the values of a column

<font size = "3">

- Consider the DataFrame ``df_movies`` created below.
- In the "country" column, change the values "American" and "Korean" to "USA" and "ROK" respectively
- Do this by using the ``.replace`` method.

In [ ]:
# Create example DataFrame - **don't change this**
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"] #List of movie titles 


country = ["American", "American", "France", "Korean", "Thailand", "Korean", "France",
    "France", "Japan", "Italy", "American"] #List of movie countries


runtime = [106, 119, 108, 120, 97, 115, 96, 91, 88, 98, 120] #List of movie runtimes in minutes

year = [2023, 1941, 2017, 2017, 2004, 2003, 1967, 1964, 1977, 1977, 1986] #List of movie release years

movie_dict = {"title" : titles, "country" : country, "runtime" : runtime, "year" : year} #Creating a 'Dictionary' from the above lists
#Essentially, the "title" is the name of the column, and titles is the list of values in that column that we defined above. 

df_movies = pd.DataFrame(movie_dict) #Then, we use the dictionary to create a DataFrame called df_movies 

# your answer here

df_movies["country"] = df_movies["country"].replace(["American", "Korean"], 
                            ["USA", "ROK"])
print()
print(df_movies)

#The reason why I write df_movies["country"] is because we are accessing the "country" column in the df_movies DataFrame.
#Then, we use the .replace() method to replace the values "American" and "Korean" with "USA" and "ROK", respectively.
#Finally, we print the updated DataFrame to see the changes.

#Why did we write df_movies["country"] twice?
#The first df_movies["country"] is to specify which column we want to modify.
#The second df_movies["country"] is to indicate that we want to replace values in that specific column.

#what does .replace() do?
#.replace() is a method in pandas that allows us to replace specific values in a DataFrame column with new values.
#In this case, we are replacing "American" with "USA" and "Korean" with "ROK" in the "country" column of the df_movies DataFrame.

                         title   country  runtime  year
0                   Past Lives       USA      106  2023
1                 Citizen Kane       USA      119  1941
2                      Revenge    France      108  2017
3                         Okja       ROK      120  2017
4                      Shutter  Thailand       97  2004
5        A Tale of Two Sisters       ROK      115  2003
6                  La Chinoise    France       96  1967
7   The Umbrellas of Cherbourg    France       91  1964
8                        House     Japan       88  1977
9                     Suspiria     Italy       98  1977
10                 Blue Velvet       USA      120  1986

<font size = "5">

(2) Recode a numeric column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories:

$\qquad$ ``` ["1941-1967","1968-1999","2000-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [12]:
# your code here

df_movies["year_brackets"] = pd.cut(x = df_movies["year"], 
                bins=[1940, 1967, 1999, float("inf")], 
                labels = ["1941-1967", "1968-1999", "2000-onwards"])

print(df_movies)

#In this code, we are creating a new column called "year_brackets" in the df_movies DataFrame.
#We use the pd.cut() function to categorize the "year" column into different brackets based on the specified bins.
#The bins are defined as [1940, 1967, 1999, float("inf")], which means:
#- The first bin includes years from 1941 to 1967
#- The second bin includes years from 1968 to 1999
#- The third bin includes years from 2000 onwards (float("inf") represents infinity)
#We also provide labels for each bin: "1941-1967", "1968-1999", and "2000-onwards".
#Finally, we print the updated DataFrame to see the new "year_brackets" column.

#What does pd.cut() do?
#pd.cut() is a function in pandas that allows us to segment and categorize continuous data into discrete bins or intervals.
#In this case, we are using it to categorize the "year" column into different brackets based on the specified bins.
#This is useful for grouping data into meaningful categories for analysis.

#So are we basically sorting the "year" into different groups for a new column?
#Yes, exactly! We are categorizing the "year" values into different groups or brackets based on the specified bins, 
#and creating a new column "year_brackets" to store these categories

                         title   country  runtime  year year_brackets
0                   Past Lives       USA      106  2023  2000-onwards
1                 Citizen Kane       USA      119  1941     1941-1967
2                      Revenge    France      108  2017  2000-onwards
3                         Okja       ROK      120  2017  2000-onwards
4                      Shutter  Thailand       97  2004  2000-onwards
5        A Tale of Two Sisters       ROK      115  2003  2000-onwards
6                  La Chinoise    France       96  1967     1941-1967
7   The Umbrellas of Cherbourg    France       91  1964     1941-1967
8                        House     Japan       88  1977     1968-1999
9                     Suspiria     Italy       98  1977     1968-1999
10                 Blue Velvet       USA      120  1986     1968-1999

<font size = "5">

(3) Rename column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Rename the column "runtime" to "runtime(minutes)"

In [13]:
# Write your answer here:
df_movies.rename(columns={"runtime" : "runtime(minutes)"}, inplace=True)

print(df_movies)

#In this code, we are renaming the column "runtime" to "runtime(minutes)" in the df_movies DataFrame.
#We use the .rename() method, where we specify the columns parameter as a dictionary that maps the old column name to the new column name.
#The inplace=True argument ensures that the changes are made directly to the original DataFrame rather than creating a new one.
#Finally, we print the updated DataFrame to see the renamed column.

                         title   country  runtime(minutes)  year year_brackets
0                   Past Lives       USA               106  2023  2000-onwards
1                 Citizen Kane       USA               119  1941     1941-1967
2                      Revenge    France               108  2017  2000-onwards
3                         Okja       ROK               120  2017  2000-onwards
4                      Shutter  Thailand                97  2004  2000-onwards
5        A Tale of Two Sisters       ROK               115  2003  2000-onwards
6                  La Chinoise    France                96  1967     1941-1967
7   The Umbrellas of Cherbourg    France                91  1964     1941-1967
8                        House     Japan                88  1977     1968-1999
9                     Suspiria     Italy                98  1977     1968-1999
10                 Blue Velvet       USA               120  1986     1968-1999

<font size = "5">

(4) Merge dataset

<font size = "3">

- Consider the DataFrames ``df_movies`` (created above) and ``df_scores`` (created below)
- Create a new dataset using  ```pd.merge()``` using <br>
"df_movies" as the primary dataset, and <br>
"df_scores" as the secondary dataset, merging on <br>
the column "title"
- You should **ONLY** merge the "imdb_score" column <br>
from the secondary dataset (not the "director" column)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging

In [14]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
scores = [7.8, 8.2, 6.4, 7.3, 7.0, 7.1, 6.9, 7.8, 7.2, 7.3, 7.7]
directors = ["Celine Song", "Orson Welles", "Coralie Fargeat", "Bong Joon Ho", 
    "Banjong Pisanthanakun", "Kim Jee-woon", "Jean-Luc Godard", "Jacques Demy", 
    "Nobuhiko Obayashi", "Dario Argento", "David Lynch"]

movie_dict2 = {"title" : titles, "imdb_score" : scores, "director" : directors}
df_scores = pd.DataFrame(movie_dict2)

# Write your answer here:

df_new = pd.merge(left = df_movies, right = df_scores[["title", "imdb_score"]], 
        on = "title", how = "left")
print(df_new)

#In this code, we are merging two DataFrames: df_movies and df_scores.
#We use the pd.merge() function to perform the merge operation.
#The left parameter specifies the left DataFrame (df_movies), and the right parameter specifies the right DataFrame (df_scores).
#We use df_scores[["title", "imdb_score"]] to select only the "title" and "imdb_score" columns from df_scores for the merge.
#The on parameter specifies the common column to merge on, which is "title" in this case.
#The how parameter specifies the type of merge to perform, which is "left" join in this case.
#Finally, we print the resulting merged DataFrame df_new to see the combined data.

#So we are merging df_movies and df_scores title columns together?
#Yes, we are merging the two DataFrames based on the "title" column, which is common to both DataFrames.
#This allows us to combine the information from both DataFrames into a single DataFrame (df_new)
#that contains all the columns from df_movies along with the corresponding.

#What about imdb_score?
#The "imdb_score" column from df_scores is included in the merged DataFrame (df_new) as well.
#Since we specified df_scores[["title", "imdb_score"]] in the right parameter,
#only the "title" and "imdb_score" columns from df_scores are included in the merge.
#So, in df_new, we will have the "imdb_score" column alongside the other columns from df_movies.

#What does on = "title", how = "left" mean?
#The on = "title" parameter specifies that we want to merge the two DataFrames based on the "title" column.
#This means that the merge will be performed by matching the values in the "title" column of both DataFrames.
#The how = "left" parameter specifies that we want to perform a left join.
#In a left join, all the rows from the left DataFrame (df_movies) are included in the merged DataFrame (df_new),
#and only the matching rows from the right DataFrame (df_scores) are included.
#If there is no match for a row in the left DataFrame, the corresponding columns from the right DataFrame will have NaN values.

#What if how was "inner" instead of "left"?
#If we used how = "inner" instead of "left", the merge would perform an inner join.
#In an inner join, only the rows that have matching values in both DataFrames based on the "title" column would be included in the merged DataFrame (df_new).
#Any rows from either DataFrame that do not have a match in the other DataFrame would be excluded from the resulting DataFrame.
#So, using how = "inner" would result in a DataFrame that only contains the movies that are present in both df_movies and df_scores.

#What about how = "right"?
#If we used how = "right" instead of "left", the merge would perform a right join.
#In a right join, all the rows from the right DataFrame (df_scores) are included in the merged DataFrame (df_new),
#and only the matching rows from the left DataFrame (df_movies) are included.
#If there is no match for a row in the right DataFrame, the corresponding columns from the left DataFrame will have NaN values.
#So, using how = "right" would result in a DataFrame that contains all the movies from df_scores,
#along with the corresponding information from df_movies where there are matches based on the "title" column.

#What about how = "outer"?
#If we used how = "outer" instead of "left", the merge would perform a full outer join.
#In a full outer join, all the rows from both DataFrames (df_movies and df_scores) are included in the merged DataFrame (df_new).
#If there is no match for a row in either DataFrame, the corresponding columns from the other DataFrame will have NaN values.
#So, using how = "outer" would result in a DataFrame that contains all the movies from both df_movies and df_scores,
#along with the corresponding information where there are matches based on the "title"

                         title   country  runtime(minutes)  year  \
0                   Past Lives       USA               106  2023
1                 Citizen Kane       USA               119  1941
2                      Revenge    France               108  2017
3                         Okja       ROK               120  2017
4                      Shutter  Thailand                97  2004
5        A Tale of Two Sisters       ROK               115  2003
6                  La Chinoise    France                96  1967
7   The Umbrellas of Cherbourg    France                91  1964
8                        House     Japan                88  1977
9                     Suspiria     Italy                98  1977
10                 Blue Velvet       USA               120  1986

   year_brackets  imdb_score
0   2000-onwards         7.8
1      1941-1967         8.2
2   2000-onwards         6.4
3   2000-onwards         7.3
4   2000-onwards         7.0
5   2000-onwards         7.1
6      1941-1967         6.9
7      1941-1967         7.8
8      1968-1999         7.2
9      1968-1999         7.3
10     1968-1999         7.7

<font size = "5">

(5) Aggregate and sort

<font size = "3">

- Using the merged dataset you created above, do the following in a single line by chaining:
    - Group the dataset by "country"
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score
    - Score by average IMBD score in **descending order**

Print the resulting DataFrame

In [18]:
# Write your answer here:

(df_new.groupby("country").agg(avg_run = ('runtime(minutes)', 'mean'),
                    max_run = ('runtime(minutes)', 'max'),
                    avg_imdb = ('imdb_score', 'mean'),
                    min_imdb = ('imdb_score', 'min')).
                    sort_values(by = "avg_imdb", ascending = False))

#In this code, we are performing a groupby operation on the df_new DataFrame based on the "country" column.
#We then use the .agg() method to calculate multiple aggregate statistics for each group.
#The statistics we are calculating are:
#- avg_run: The average runtime in minutes for each country (calculated using the mean function)
#- max_run: The maximum runtime in minutes for each country (calculated using the max function)
#- avg_imdb: The average IMDb score for each country (calculated using the mean function)
#- min_imdb: The minimum IMDb score for each country (calculated using the min function)
#Finally, we use .sort_values() to sort the resulting DataFrame by the "avg_imdb" column in descending order (highest to lowest).
#This allows us to see the countries with the highest average IMDb scores at the top of the DataFrame.
#The final output is a DataFrame that shows the average and maximum runtime, as well as the average and 
#minimum IMDb scores for each country, sorted by average IMDb score.

#What does groupby() do?
#The groupby() function in pandas is used to group data based on one or more columns.
#In this case, we are grouping the df_new DataFrame by the "country" column.
#This means that all the rows with the same country value will be grouped together,
#allowing us to perform aggregate calculations on each group separately.
#For example, all the movies from the USA will be grouped together, all the movies from France will be grouped together, and so on.
#This is useful for analyzing data at a more granular level, such as calculating statistics for each country individually.
#The result of the groupby operation is a GroupBy object, which we can then use to perform aggregate calculations using the .agg() method. column.
#This allows us to see all the movies from both DataFrames, regardless of whether they have matches in the other DataFrame or not.

#What does .agg() do?
#.agg() is a method in pandas that allows us to perform multiple aggregate calculations on grouped data.
#In this case, we are using .agg() to calculate the average and maximum runtime, as well as the average and minimum IMDb scores for each country group.
#We specify the calculations we want to perform using a dictionary, where the keys are the names of the new columns 
# we want to create (e.g., "avg_run", "max_run", "avg_imdb", "min") and the values are tuples 
# that specify the column to aggregate and the aggregation function to use (e.g., ('runtime(minutes)', 'mean')).
#This allows us to compute multiple statistics for each group in a single operation, 
# resulting in a DataFrame that summarizes the data for each country.

#Are there other inputs like 'mean', 'max', 'min' for .agg()?
#Yes, there are many other aggregation functions that can be used with .agg().
#Some common ones include:
#- 'sum': Calculates the sum of values
#- 'count': Counts the number of non-null values
#- 'median': Calculates the median of values
#- 'std': Calculates the standard deviation of values
#- 'var': Calculates the variance of values
#- 'first': Returns the first value in the group
#- 'last': Returns the last value in the group

             avg_run  max_run  avg_imdb  min_imdb
country
USA       115.000000      120  7.900000       7.7
Italy      98.000000       98  7.300000       7.3
Japan      88.000000       88  7.200000       7.2
ROK       117.500000      120  7.200000       7.1
France     98.333333      108  7.033333       6.4
Thailand   97.000000       97  7.000000       7.0

<font size = "5">

(6) Query and Aggregate

<font size = "3">

Using the merged dataset you created above, do the following in a single line by chaining:

- Subset the observations for 'country == France' using ```.query()```
- Sort the values by year (oldest first)
- Extract the two oldest movies

Print the resulting DataFrame to the screen

In [20]:
# Write your answer here:
df_new.query("country == 'France'").sort_values(by = "year").iloc[:2,:]

#In this code, we are filtering the df_new DataFrame to include only the rows where the "country" column is equal to 'France'.
#We use the .query() method to perform this filtering operation.
#Next, we use .sort_values() to sort the filtered DataFrame by the "year" column in ascending order (oldest to newest).
#Finally, we use .iloc[:2,:] to select the first two rows of the sorted DataFrame, which correspond to the two oldest movies from France.
#The final output is a DataFrame that shows the details of the two oldest movies from France.

#What does .query() do?
#.query() is a method in pandas that allows us to filter a DataFrame based on a boolean expression.
#In this case, we are using .query("country == 'France'") to filter the df_new DataFrame to include only the rows where the "country" column is equal to 'France'.
#This is a convenient way to filter data without having to use more complex indexing or boolean masking techniques.
#The result of the .query() operation is a new DataFrame that contains only the rows that satisfy the specified condition.

#What does .iloc[:2,:] do?
#.iloc[:2,:] is used to select specific rows and columns from a DataFrame based on their integer position.
#In this case, .iloc[:2,:] is selecting the first two rows (indicated by :2) and all columns (indicated by :) of the DataFrame.
#The first part (:2) specifies the row indices to select, which means we want the rows at index 0 and 1 (the first two rows).
#The second part (:,) specifies that we want to include all columns in the selection.
#So, the result of .iloc[:2,:] is a DataFrame that contains only the first two rows of the original DataFrame, along with all the columns.

,title,country,runtime(minutes),year,year_brackets,imdb_score
7,The Umbrellas of Cherbourg,France,91,1964,1941-1967,7.8
6,La Chinoise,France,96,1967,1941-1967,6.9